#ifndef GENETIC_ALGORITHM
#define GENETIC_ALGORITHM

//parametre GENETIC_ALGORITHM
#define NBR_POPULATION 1000
#define FRQ_MUTATION 0.08
#define NBR_SELECTION 1000
#define NBR_RANDOM 100
#define TIMEOUT 60000


//parametre machine learning
#define RANDOM_VALUE_W 20
#define RANDOM_VALUE_B 20


#define SCREEN_WIDTH 1500
#define SCREEN_HEIGHT 1000
#define OUTSCREEN_W 400

#endif